#[target.'cfg(target_os = "linux")']
#rustflags = ["-C", "link-arg=-nostartfiles"]

[build]
target = "targets/i686-nucloid.json"

[target.i686-nucloid]
rustflags = [
    "-C", "link-arg=-Ttargets/i686.ld",
    "-C", "link-arg=-nostartfiles"
]

[target.x86_64-nucloid]
rustflags = [
    "-C", "link-arg=-Ttargets/x86_64.ld",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-n"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
